### PR TITLE
Finish "Our memorable moments" page

### PR DESCRIPTION
**Pull request by khaitruong922**
Please review the file "moments.html" and I will merge it to the index.html if you guys think this one is good enough.

### CODE REVIEW

**Comment by hungthezorba** [comment]
Very neat and tidy, almost close to be approved. Just need to make it responsive for smaller devices
image

image

**Comment by khaitruong922** [comment]
I am not really proficient in CSS so which one should I use to achieve responsiveness for the timeline layout: grid or flexbox?

**Comment by khaitruong922** [comment]
@hungthezorba I just use the responsive grid to improve the text and image layout on small screen. The vertical timeline is also hidden in small screen too.

**Review by hungthezorba — COMMENTED** [review]
Sorry for late reply, the responsive is good now. It's good to be merged, I will changed this to merged in to dev branch after reviewed other works as well.

**Pull request merged**
